<?php
/**
 * @file
 * ua_brand_demo.module
 */

/**
 * Implements hook_migrate_api().
 */
function ua_brand_demo_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'ua_brand_demo' => array(
        'title' => t('UA Brand Demo Content'),
      ),
    ),
    'migrations' => array(
      'UaBrandDemoPage' => array(
        'class_name' => 'UaBrandDemoPage',
        'group_name' => 'ua_brand_demo',
      ),
      'UaBrandDemoFeature' => array(
        'class_name' => 'UaBrandDemoFeature',
        'group_name' => 'ua_brand_demo',
      ),
      'UaBrandDemoMenu' => array(
        'class_name' => 'UaBrandDemoMenu',
        'group_name' => 'ua_brand_demo',
      ),
    ),
  );
  return $api;
}

/**
 * Helpfer function to import demo content for apps using Migrate.
 */
function _ua_brand_demo_import_demo_content($classes = array()) {
  // Ensure that migration classes are registered.
  migrate_get_module_apis(TRUE);

  // Process the migrations to import demo content.
  foreach ($classes as $class) {
    // Register the Migration class since auto-registration is not supported
    // since Migrate module version 2.6
    Migration::registerMigration($class);

    // Get a handle on our migration class.
    $migration = Migration::getInstance($class);

    // Disable message output from migrate ince this import is used within
    // the context of the Apps module where these messages make no sense.
    Migration::setDisplayFunction('_ua_brand_demo_null_message');

    // Process the migration.
    $migration->processImport();
  }
}

/**
 * Helpfer function to import demo content for apps using Migrate.
 */
function _ua_brand_demo_rollback_demo_content($classes = array()) {
  // Roll back the migrations to delete the demo content.
  foreach ($classes as $class) {
    // Get a handle on our migration class.
    $migration = Migration::getInstance($class);

    // Disable message output from migrate ince this import is used within
    // the context of the Apps module where these messages make no sense.
    Migration::setDisplayFunction('_ua_brand_demo_null_message');

    // Roll back the migration.
    $migration->processRollback();

    // deregister the Migration classes since it will not exist after the
    // module is disabled.
    Migration::deregisterMigration($class);
  }
}

/**
 * Helpfer function to import demo content for apps using Migrate.
 */
function _ua_brand_demo_null_message($message, $level) {
  return;
}
