<?php
/**
 * @file
 * ua_demo.module
 */

/**
 * Implements hook_migrate_api().
 */
function ua_demo_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'ua_demo' => array(
        'title' => t('UA Demo Content'),
      ),
    ),
    'migrations' => array(
      'UaDemoPage' => array(
        'class_name' => 'UaDemoPage',
        'group_name' => 'ua_demo',
      ),
      'UaDemoCarouselItem' => array(
        'class_name' => 'UaDemoCarouselItem',
        'group_name' => 'ua_demo',
      ),
      'UaDemoPerson' => array(
        'class_name' => 'UaDemoPersonMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoUnitTerm' => array(
        'class_name' => 'UaDemoUnitTermMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoUnit' => array(
        'class_name' => 'UaDemoUnitMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoNews' => array(
        'class_name' => 'UaDemoNewsMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoNewsContact' => array(
        'class_name' => 'UaDemoNewsContactMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoMenu' => array(
        'class_name' => 'UaDemoMenu',
        'group_name' => 'ua_demo',
      ),
    ),
  );
  return $api;
}

