<?php
/**
 * @file
 * ua_demo.module
 */

/**
 * Implements hook_migrate_api().
 */
function ua_demo_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'ua_demo' => array(
        'title' => t('UA Demo Content'),
      ),
    ),
    'migrations' => array(
      'UaDemoPage' => array(
        'class_name' => 'UaDemoPageMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoCarouselItem' => array(
        'class_name' => 'UaDemoCarouselItemMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoPerson' => array(
        'class_name' => 'UaDemoPersonMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoUnitTerm' => array(
        'class_name' => 'UaDemoUnitTermMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoUnit' => array(
        'class_name' => 'UaDemoUnitMigration',
        'group_name' => 'ua_demo',
        'dependencies' => array('UaDemoUnitTerm'),
      ),
      'UaDemoNews' => array(
        'class_name' => 'UaDemoNewsMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoNewsContact' => array(
        'class_name' => 'UaDemoNewsContactMigration',
        'group_name' => 'ua_demo',
        'dependencies' => array('UaDemoNews'),
      ),
      'UaDemoEvent' => array(
        'class_name' => 'UaDemoEventMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoEventContact' => array(
        'class_name' => 'UaDemoEventContactMigration',
        'group_name' => 'ua_demo',
        'dependencies' => array('UaDemoEvent'),
      ),
      'UaDemoPublicationTerm' => array(
        'class_name' => 'UaDemoPublicationTermMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoPublication' => array(
        'class_name' => 'UaDemoPublicationMigration',
        'group_name' => 'ua_demo',
        'dependencies' => array('UaDemoPublicationTerm'),
      ),
      'UaDemoProgramTerm' => array(
        'class_name' => 'UaDemoProgramTermMigration',
        'group_name' => 'ua_demo',
      ),
      'UaDemoProgram' => array(
        'class_name' => 'UaDemoProgramMigration',
        'group_name' => 'ua_demo',
        'dependencies' => array('UaDemoProgramTerm'),
      ),
      'UaDemoNavigation' => array(
        'class_name' => 'UaDemoNavigationMigration',
        'group_name' => 'ua_demo',
        'dependencies' => array(
          'UaDemoPage',
          'UaDemoPerson',
          'UaDemoNews',
          'UaDemoUnit',
          'UaDemoProgram',
          'UaDemoPublication',
        ),
      ),
    ),
  );
  return $api;
}

