<?php
/**
 * @file
 * ua_demo.install
 */

/**
 * Implements hook_enable().
 */
function ua_demo_enable() {
  _ua_demo_import_demo_content(array('UaDemoPage', 'UaDemoMenu', 'UaDemoCarouselItem'));
  variable_set('site_frontpage', 'primus');
}

/**
 * Implements hook_disable().
 */
function ua_demo_disable() {
  _ua_demo_rollback_demo_content(array('UaDemoMenu', 'UaDemoPage', 'UaDemoCarouselItem'));
}
