<?php
/**
 * @file
 * uaqs_demo.module
 */

/**
 * Implements hook_migrate_api().
 */
function uaqs_demo_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'uaqs_demo' => array(
        'title' => t('UAQS Demo Content'),
      ),
    ),
    'migrations' => array(
      'UaqsDemoPage' => array(
        'class_name' => 'UaqsDemoPageMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoCarouselItem' => array(
        'class_name' => 'UaqsDemoCarouselItemMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoContactSummary' => array(
        'class_name' => 'UaqsDemoContactSummaryMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoCard' => array(
        'class_name' => 'UaqsDemoCardMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoPerson' => array(
        'class_name' => 'UaqsDemoPersonMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoUnitTerm' => array(
        'class_name' => 'UaqsDemoUnitTermMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoUnit' => array(
        'class_name' => 'UaqsDemoUnitMigration',
        'group_name' => 'uaqs_demo',
        'dependencies' => array('UaqsDemoUnitTerm'),
      ),
      'UaqsDemoNews' => array(
        'class_name' => 'UaqsDemoNewsMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoNewsContact' => array(
        'class_name' => 'UaqsDemoNewsContactMigration',
        'group_name' => 'uaqs_demo',
        'dependencies' => array('UaqsDemoNews'),
      ),
      'UaqsDemoEvent' => array(
        'class_name' => 'UaqsDemoEventMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoEventContact' => array(
        'class_name' => 'UaqsDemoEventContactMigration',
        'group_name' => 'uaqs_demo',
        'dependencies' => array('UaqsDemoEvent'),
      ),
      'UaqsDemoColumnImage' => array(
        'class_name' => 'UaqsDemoColumnImageMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoHeadedText' => array(
        'class_name' => 'UaqsDemoHeadedTextMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoPlainText' => array(
        'class_name' => 'UaqsDemoPlainTextMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoFlexiblePage' => array(
        'class_name' => 'UaqsDemoFlexiblePageMigration',
        'group_name' => 'uaqs_demo',
        'dependencies' => array(
          'UaqsDemoColumnImage',
          'UaqsDemoHeadedText',
          'UaqsDemoPlainText',
        ),
      ),
      'UaqsDemoPublicationTerm' => array(
        'class_name' => 'UaqsDemoPublicationTermMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoPublication' => array(
        'class_name' => 'UaqsDemoPublicationMigration',
        'group_name' => 'uaqs_demo',
        'dependencies' => array('UaqsDemoPublicationTerm'),
      ),
      'UaqsDemoProgramTerm' => array(
        'class_name' => 'UaqsDemoProgramTermMigration',
        'group_name' => 'uaqs_demo',
      ),
      'UaqsDemoProgram' => array(
        'class_name' => 'UaqsDemoProgramMigration',
        'group_name' => 'uaqs_demo',
        'dependencies' => array('UaqsDemoProgramTerm'),
      ),
      'UaqsDemoNavigation' => array(
        'class_name' => 'UaqsDemoNavigationMigration',
        'group_name' => 'uaqs_demo',
        'dependencies' => array(
          'UaqsDemoPage',
          'UaqsDemoPerson',
          'UaqsDemoNews',
          'UaqsDemoUnit',
          'UaqsDemoProgram',
          'UaqsDemoPublication',
        ),
      ),
    ),
  );
  return $api;
}

