<?php
/**
 * @file
 * Code for the UA Featured Content feature.
 */

include_once 'ua_featured_content.features.inc';

/**
 * Implements hook_views_api_alter().
 *
 * hook_views_api() is implemented by features but we need to add our views
 * template path.
 */
function ua_featured_content_views_api_alter(&$apis) {
  if (!empty($apis['ua_featured_content']) && $apis['ua_featured_content']['api'] == '3.0') {
    $apis['ua_featured_content']['template path'] = drupal_get_path('module', 'ua_featured_content') . '/theme';
  }
}
