<?php
/**
 * @file
 * Code for the UA Featured Content feature.
 */

include_once 'ua_featured_content.features.inc';

/**
 * Implements hook_views_api_alter().
 *
 * hook_views_api() is implemented by features but we need to add our views
 * template path.
 */
function ua_featured_content_entity_info_alter(&$entity_info) {
     $entity_info['node']['view modes']['ua_featured_content'] = array(
        'label' => t('ua_featured_content_display'),
        'custom settings' => TRUE,
      );
}
function ua_featured_content_preprocess_node(&$vars) {
  drupal_add_js(drupal_get_path('module', 'ua_featured_content') . '/js/modernizr.custom.7860.js');
  drupal_add_js(drupal_get_path('module', 'ua_featured_content') . '/js/ua_featured_content.js');
  $wrapper = entity_metadata_wrapper('node', $vars['node']);
  $nid = $wrapper->getIdentifier();
  $path_to_node = url("node/$nid");
  $has_cta = FALSE;
  $vars['ua_featured_content']['image_path'] = '';
  if (field_info_instance('node', 'field_slide_image', $wrapper->getBundle())) {
      $slide_image_uri = $wrapper->field_slide_image->file->value()->uri;
      $slide_styled_path = image_style_url('flexslider_full', $slide_image_uri);
      $vars['ua_featured_content']['image_path'] = $slide_styled_path;
  }
  if (field_info_instance('node', 'field_call_to_action', $wrapper->getBundle())) {
    $has_cta = $wrapper->field_call_to_action->value();
    if (isset($has_cta)){
      $vars['ua_featured_content']['path'] = $wrapper->field_call_to_action->url->value();
    }
    else
    {
      $vars['ua_featured_content']['path'] = $path_to_node;
    }
  }
  else
  {
    $vars['ua_featured_content']['path'] = $path_to_node;
  }
  if ($vars['view_mode'] == 'ua_featured_content') {
      $vars['theme_hook_suggestions'][] = 'node__ua_featured_content';
  }
}
function ua_featured_content_theme_registry_alter(&$theme_registry) {
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'ua_featured_content');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}



